version: '3.7'
services:
  db:
    image: postgres:12.6
    restart: always
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - ./src/shared/data/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3000:80"
    links:
      - "db:pgsql-server"